apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgd
  namespace: bgd
  labels:
    app: bgd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bgd
  template:
    metadata:
      labels:
        app: bgd
    spec:
      containers:
        - name: bgd
          image: rkskek0718/bgd-arm64:1.0
          env:
            - name: COLOR
              value: "blue"